### ISSUE TITLE
highway tools raw material shulker issue

### ISSUE THREAD

**Issue by FighterJet16** [lambda-plugins/HighwayTools#38]
When it opens the shulker it doesn't collect the maximum amount of obby that can fit in my inventory from the raw material shulker which causes it to pick up the empty shulker again which causes my inventory to become full of empty shulks after a while

**Comment by Avanatiker** [comment]
its fixed in 10.1+

**Comment by FighterJet16** [comment]
> its fixed in 10.1+

I still have the issue I also have a recording of it happenin

https://user-images.githubusercontent.com/86580208/150692685-3cec9493-1b8c-4f30-8702-5645960fc581.mp4
